'use strict';
/**
 * Records with translated fields.
 */
module.exports = {
    'ACTI': ['ATTX', 'FULL'],
    'ALCH': ['DESC', 'DNAM', 'FULL'],
    'AMMO': ['FULL', 'ONAM', 'DESC', 'FULL'],
    'ARMO': [ 'DESC', 'FULL' ],
    'AVIF': ['ANAM', 'DESC', 'FULL'],
    'BPTD': ['BPTN'],
    'BOOK': ['DESC', 'FULL'],
    'CELL': ['FULL'],
    'CLAS': ['FULL'],
    'CLFM': ['FULL'],
    'CMPO': ['FULL'],
    'COBJ': ['DESC'],
    'COLL': ['DESC'],
    'CONT': ['FULL'],
//    'DIAL': ['FULL'],
    'DOOR': ['CNAM', 'FULL', 'ONAM'],
    'ENCH': ['FULL'],
    'EXPL': ['FULL'],
    'FACT': ['FULL'],
    'FLOR': ['ATTX', 'FULL'],
    'FLST': ['FULL'],
    'FURN': ['ATTX', 'FULL'],
    'GMST': ['DATA'],
    'HAZD': ['FULL'],
    'HDPT': ['FULL'],
//    'INFO': ['NAM1', 'RNAM'],
    'INGR': ['FULL'],
    'INNR': ['WNAM'],
    'KEYM': ['FULL'],
    'KYWD': ['FULL'],
    'LCTN': ['FULL'],
    'LIGH': ['FULL'],
    'LSCR': ['DESC'],
    'LVLI': ['ONAM'],
    'MESG': ['DESC', 'FULL', 'ITXT', 'NNAM'],
    'MGEF': ['DNAM', 'FULL'],
    'MISC': ['FULL'],
    'MSTT': ['FULL'],
    'NOTE': ['FULL'],
    'NPC_': ['FULL', 'SHRT'],
    'OMOD': ['DESC', 'FULL'],
    'PERK': ['DESC', 'EPF2', 'FULL'],
    'PROJ': ['FULL'],
    'QUST': ['CNAM', 'FULL', 'NNAM'],
    'RACE': ['DESC', 'FMRN', 'FULL', 'MPPN', 'TTGP'],
    'REFR': ['FULL'],
    'REGN': ['RDMP'],
    'SCOL': ['FULL'],
    'SNCT': ['FULL'],
    'SPEL': ['FULL'],
    'STAT': ['FULL'],
    'TACT': ['FULL'],
    'TERM': ['BTXT', 'FULL', 'ITXT', 'NAM0', 'RNAM', 'UNAM', 'WNAM'],
    'WATR': ['FULL'],
    'WEAP': ['DESC', 'FULL'],
    'WRLD': ['FULL']
};
